### ISSUE TITLE
PHP error 'Undefined variable: cacheKey1' when specifying an until or for parameter

### ISSUE THREAD

**Issue by johndwells** [mmikkel/CacheFlag-Craft#6]
I have the following in my template:

    {% cacheflag flagged "home" for 1 week %}
        Hello, world!
    {% endcacheflag %}

And when I hit the page in the browser while `devMode` is on, I get:

    Undefined variable: cacheKey1

Any ideas what it could be?

**Comment by johndwells** [comment]
Ah - I think this is only being thrown either in Live Preview or when previewing an un-published entry.  Hopefully that helps!

**Comment by mmikkel** [comment]
Thanks for contributing, John! I'll investigate ASAP. Feel free to submit a pull request though, if you find the error (and a fix) :)

**Comment by mvdt** [comment]
I guess this is the same error for me.

> fsdfsdfd

```
2017/02/27 13:07:42 [error] [php] Undefined variable: cacheKey1 (/srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code:151)
Stack trace:
#0 /srv/data/web/vhosts/demo.com/craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_74752ba83135b914fb95a902b53150d6d1552a957ae89dfb5750fa13e5d3d239->displayWithErrorHandling()
#1 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Template.php(355): __TwigTemplate_74752ba83135b914fb95a902b53150d6d1552a957ae89dfb5750fa13e5d3d239->displayWithErrorHandling()
#2 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(76): __TwigTemplate_74752ba83135b914fb95a902b53150d6d1552a957ae89dfb5750fa13e5d3d239->display()
#3 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_d1ae3e2e56b8e16b6fa4fe07cad070a231faf9487c267f42b985ac2e0a0d2d36->doDisplay()
#4 /srv/data/web/vhosts/demo.com/craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_d1ae3e2e56b8e16b6fa4fe07cad070a231faf9487c267f42b985ac2e0a0d2d36->displayWithErrorHandling()
#5 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Template.php(355): __TwigTemplate_d1ae3e2e56b8e16b6fa4fe07cad070a231faf9487c267f42b985ac2e0a0d2d36->displayWithErrorHandling()
#6 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(27): __TwigTemplate_d1ae3e2e56b8e16b6fa4fe07cad070a231faf9487c267f42b985ac2e0a0d2d36->display()
#7 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Template.php(387): __TwigTemplate_5dc9a2c4e8feb6114858062f6351b088ce3f4ff3eea7380a39a5b91acb19ac36->doDisplay()
#8 /srv/data/web/vhosts/demo.com/craft/app/etc/templating/BaseTemplate.php(26): __TwigTemplate_5dc9a2c4e8feb6114858062f6351b088ce3f4ff3eea7380a39a5b91acb19ac36->displayWithErrorHandling()
#9 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Template.php(355): __TwigTemplate_5dc9a2c4e8feb6114858062f6351b088ce3f4ff3eea7380a39a5b91acb19ac36->displayWithErrorHandling()
#10 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Template.php(366): __TwigTemplate_5dc9a2c4e8feb6114858062f6351b088ce3f4ff3eea7380a39a5b91acb19ac36->display()
#11 /srv/data/web/vhosts/demo.com/craft/app/vendor/twig/twig/lib/Twig/Environment.php(347): __TwigTemplate_5dc9a2c4e8feb6114858062f6351b088ce3f4ff3eea7380a39a5b91acb19ac36->render()
#12 /srv/data/web/vhosts/demo.com/craft/app/services/TemplatesService.php(256): Craft\TwigEnvironment->render()
#13 /srv/data/web/vhosts/demo.com/craft/app/controllers/BaseController.php(74): Craft\TemplatesService->render()
#14 /srv/data/web/vhosts/demo.com/craft/app/controllers/EntriesController.php(978): Craft\EntriesController->renderTemplate()
#15 /srv/data/web/vhosts/demo.com/craft/app/controllers/EntriesController.php(406): Craft\EntriesController->_showEntry()
#16 /srv/data/web/vhosts/demo.com/craft/app/framework/web/actions/CInlineAction.php(49): Craft\EntriesController->actionPreviewEntry()
#17 /srv/data/web/vhosts/demo.com/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#18 /srv/data/web/vhosts/demo.com/craft/app/framework/web/CController.php(286): Craft\EntriesController->runAction()
#19 /srv/data/web/vhosts/demo.com/craft/app/framework/web/CController.php(265): Craft\EntriesController->runActionWithFilters()
#20 /srv/data/web/vhosts/demo.com/craft/app/framework/web/CWebApplication.php(282): Craft\EntriesController->run()
#21 /srv/data/web/vhosts/demo.com/craft/app/etc/web/WebApp.php(817): Craft\WebApp->runController()
#22 /srv/data/web/vhosts/demo.com/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#23 /srv/data/web/vhosts/demo.com/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#24 /srv/data/web/vhosts/demo.com/craft/app/index.php(62): Craft\WebApp->run()
#25 /srv/data/web/vhosts/demo.com/htdocs/index.php(21): require_once()
REQUEST_URI=/artists/antoine-rix
```

**Comment by pauliusef** [comment]
Hello, I created a PR #8 that fixes this issue. I think this is a correct way to handle the situation when entry is viewed in Live Preview or an unpublished entry is previewed with a token.
